"""Sphinx configuration for Artefactual documentation."""

import os
from pathlib import Path, PurePosixPath

import artefactual

# Project information
project = "Artefactual"
copyright = "2025, Artefact Research Center"  # noqa: A001
author = "Hicham Randrianarivo, Gauthier Jeannin, Charles Moslonka"

# Read from the installed package, which hatch-vcs derives from the git tag, so the site
# names a version that exists rather than one restated here and left to drift. A build
# from an untagged commit carries a `.dev` segment, which is what marks it unreleased.
release = artefactual.__version__
version = ".".join(release.split(".")[:2])
_is_development_build = ".dev" in release

# Where the published site lives. Fixed rather than derived, because the version switcher
# has to name one URL that every version of the site agrees on: each release ships a copy
# of this file, and they must all point at the same switcher.json, or an old page cannot
# offer the versions released after it.
SITE_URL = "https://artefactory.github.io/artefactual"

# The site is one directory per release, so a page has to say which release it belongs to.
html_baseurl = f"{SITE_URL}/{release}/" if not _is_development_build else SITE_URL

# Just the project. The version belongs in the switcher, which names it once and makes it
# navigable; repeating it here would also put the full local version
# (2026.8.1.post1.dev36+j772a71f36.d20260911) in the site's most prominent label on every
# build that is not a release.
# Just the project name. This is the navbar's leftmost element and the switcher sits
# beside it: "Artefactual documentation" is wide enough that the two cannot share a row,
# and the theme wraps rather than shrinks, which costs a second navbar row on every page.
# The browser tab still reads "<page> - Artefactual" because the theme appends it.
html_title = project

# Extensions
extensions = [
    "myst_nb",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.githubpages",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx_autodoc_typehints",
    "sphinx_llms_txt",
    "sphinxcontrib.mermaid",
]

# Optional extras autodoc must not need installed to document the modules that guard
# their imports behind TYPE_CHECKING.
autodoc_mock_imports = ["langfuse"]

# Autodoc settings
autodoc_default_options = {
    "members": True,
    "undoc-members": False,
    "show-inheritance": True,
}
autosummary_generate = True

# Napoleon settings. The codebase documents with Google-style Args:/Returns:/Raises:
# sections; NumPy style stays on so a contributor using it is still parsed.
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_use_param = True
napoleon_use_rtype = True

# Intersphinx mapping
intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    # The detectors subclass Pipeline and LogisticRegression, so their inherited
    # docstrings reference sklearn's glossary and labels.
    "sklearn": ("https://scikit-learn.org/stable/", None),
}

# MyST settings
myst_heading_anchors = 3
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    # `{glue:text}` in prose renders a value computed in a cell, so a sentence quoting a
    # score cannot drift from the cell that produced it.
    "substitution",
]

# MyST-NB settings
#
# The examples are MyST Markdown, not `.ipynb`: the source a contributor reviews is the code
# and the prose, with no output blobs and no execution counts, so a diff reads as a diff.
# The `.ipynb` a reader downloads is generated by the build.
#
# The published site runs its notebooks and publishes what it got. Every other build renders
# the cells without outputs, because executing needs the network and would make a pull
# request wait on the Hugging Face Hub -- so a pull request shows the code that will run,
# not the results it produced somewhere else.
#
# A notebook that cannot run unattended opts out in its own front matter
# (`mystnb: {execution_mode: "off"}`), which is where the reason belongs: it travels with
# the notebook rather than sitting in a list here that nobody updates.
nb_execution_mode = "force" if os.environ.get("ARTEFACTUAL_EXECUTE_NOTEBOOKS") else "off"

# A notebook that reaches the Hub has to survive a slow answer; the default is 30 seconds.
nb_execution_timeout = 600

# A cell that raises stops the build with its traceback in the log. The default reports a
# warning and renders the page with the failure inside it, which -W would turn into an
# error too -- but with the traceback left in the page rather than in the CI output.
nb_execution_raise_on_error = True
nb_execution_show_tb = True

# nbsphinx rendered cell stderr as a styled block, which -W never saw: a notebook could
# warn its way through a release. As a Sphinx warning it fails the build instead. The build
# job quiets the progress bars that would otherwise trip it.
nb_output_stderr = "warn"

# Markdown cells are MyST, not CommonMark, so notebook prose can cross-reference the API --
# ``{py:class}`~artefactual.scoring.WEPR` `` links to the page documenting it.
nb_render_markdown_format = "myst"

# Progress bars, off before any kernel starts. MyST-NB spawns the kernel from this process,
# so it inherits what is set here -- which makes a local build behave as the release build
# does without every contributor having to know the list. Each of these is read by a
# different library, and any one of them left on puts a bar in the page.
for _quiet in (
    "HF_HUB_DISABLE_PROGRESS_BARS",
    "HF_DATASETS_DISABLE_PROGRESS_BARS",
    "TQDM_DISABLE",
):
    os.environ.setdefault(_quiet, "1")
os.environ.setdefault("TRANSFORMERS_VERBOSITY", "error")

# A progress bar under a kernel is an ipywidget, and its output carries a widget-view mime
# the published page has no widget runtime to render. MyST-NB falls back to printing that
# payload, so the page showed a line of raw JSON -- a model id and a schema version -- where
# the bar had been. Dropping the mime makes it fall through to the plain-text alternative
# the same output carries, which for a finished bar is nothing.
nb_mime_priority_overrides = [
    ("html", "application/vnd.jupyter.widget-view+json", None),
    ("html", "application/vnd.jupyter.widget-state+json", None),
]

# A `{glue:text}` reads a value a cell computed, so a build that runs no cells has none to
# read and warns once per reference -- which -W would turn into a failure of every pull
# request. Suppressed only there. The release build executes, so a key that is misspelled
# or whose cell stopped producing it still fails, which is when it matters.
if not os.environ.get("ARTEFACTUAL_EXECUTE_NOTEBOOKS"):
    suppress_warnings = ["mystnb.glue"]

# Every notebook page carries its own two entry points in the article header: open the
# notebook in Colab, or download the `.ipynb`. They live in a theme component
# (`_templates/notebook-buttons.html`) filled in by the `html-page-context` handler below,
# rather than in the notebook's own first cell, so they render as part of the page
# furniture instead of as the first paragraph of its content.
#
# The `.ipynb` both point at does not exist in the repository: the source of an example is
# its MyST Markdown, and the notebook is written here, into the site, beside the page it
# belongs to. MyST-NB does not do this -- its `jupyter_execute` folder is a build sibling
# for images, not part of the output -- so the build-finished handler below writes them.
_NOTEBOOK_SOURCES = Path(__file__).parent / "examples"


def _is_example_notebook(docname: str) -> bool:
    """Say whether a docname is one of the executable examples rather than their index."""
    return (
        docname.startswith("examples/")
        and (_NOTEBOOK_SOURCES / f"{PurePosixPath(docname).name}.md").is_file()
        and not docname.endswith("/index")
    )


# Colab loads a notebook from GitHub by owner, repo, branch and path, and all four have to
# be right or the link 404s -- so the first two come from the environment where CI sets
# them, and fall back to this repository's own values for a local build. A fork's docs then
# link into the fork.
#
# The branch is `gh-pages`, not the source branch: that branch is the published site, which
# is where the generated notebooks live, and it keeps one directory per release -- so a
# reader on the 2026.9.1 pages opens the 2026.9.1 notebook rather than whatever `main` has
# become since. A development build has no directory of its own and points at `stable`.
_REPOSITORY = os.environ.get("GITHUB_REPOSITORY", "artefactory/artefactual")
_ARCHIVE_DIR = "stable" if _is_development_build else release
_COLAB = f"https://colab.research.google.com/github/{_REPOSITORY}/blob/gh-pages/{_ARCHIVE_DIR}/"


def _notebook_buttons(app, pagename: str, templatename: str, context: dict, doctree) -> None:  # noqa: ARG001
    """Give an example page the two values its header component renders, and others none.

    The download href is a bare filename, so it resolves whatever the depth of the page and
    stays same-origin -- which is what makes the browser honour `download` rather than
    navigating to a screenful of JSON. The theme's own "Show Source" link is not this; it
    serves `_sources/<name>.md.txt`, which renders as text.

    Every page that is not an example leaves `notebook_filename` unset, and the component
    renders nothing.
    """
    if not _is_example_notebook(pagename):
        return
    name = f"{PurePosixPath(pagename).name}.ipynb"
    context["notebook_filename"] = name
    context["colab_url"] = f"{_COLAB}{pagename}.ipynb"


def _write_notebooks(app, exception) -> None:
    """Write each example's `.ipynb` into the built site, beside the page it produced.

    The notebook carries the code and the prose and no outputs: a reader downloading it is
    going to run it, and the results of this build are already on the page they downloaded
    it from. Skipped when the build failed, so a broken build publishes no notebooks.
    """
    if exception is not None or app.builder.name != "html":
        return
    import jupytext

    out = Path(app.outdir) / "examples"
    out.mkdir(parents=True, exist_ok=True)
    for source in sorted(_NOTEBOOK_SOURCES.glob("*.md")):
        if not _is_example_notebook(f"examples/{source.stem}"):
            continue
        jupytext.write(jupytext.read(source), out / f"{source.stem}.ipynb", fmt="ipynb")


def setup(app) -> None:
    """Register the handlers that generate the notebooks and fill the header buttons."""
    app.connect("html-page-context", _notebook_buttons)
    app.connect("build-finished", _write_notebooks)


# sphinx-llms-txt settings
#
# The extension reads Sphinx *source* files, not rendered output, which decides everything
# below:
#
#   - `_autosummary/*` stubs are four lines of `.. automodule::` each. Rendered they become
#     the API reference; as source they are empty, so including them puts 19 links to
#     nothing in llms.txt and 18 bare directives in llms-full.txt.
#   - Notebooks are read as raw `.ipynb` JSON, outputs and all. Unfiltered they were 89% of
#     llms-full.txt, and the HTML pages remain the readable form of them.
#
# The API is supplied instead as the source itself, via `llms_txt_code_files`. That is
# strictly more than autodoc would have rendered: the same docstrings, plus the code and
# the comments explaining it.
#
# The notebooks are globbed rather than matched by name. `examples/*_demo` covered the three
# that existed when this was written, and a notebook called anything else silently landed in
# llms-full.txt as its own source -- one of them carrying a fixture of per-token logprob
# arrays. Globbing the directory cannot go stale that way. `examples/index` is prose and
# stays.
_DOCS = Path(__file__).parent
_NOTEBOOKS = [f"examples/{path.stem}" for path in sorted((_DOCS / "examples").glob("*.ipynb"))]
llms_txt_exclude = ["_autosummary/*", *_NOTEBOOKS, "presentations/index"]
# Each file is listed explicitly rather than globbed with `+:../src/artefactual/**/*.py`,
# because the extension's `-:` exclusions do not work for paths outside the source
# directory: it compares resolved include paths against unresolved exclude globs, so
# `-:../src/**/__init__.py` never matches and every package `__init__.py` is pulled in. They
# are dropped here instead, since eight sections all titled `__init__.py` help nobody.
#
# Titles are bare filenames whatever `llms_txt_code_base_path` is set to -- the extension
# derives them with `relative_to(srcdir)`, which raises for anything outside `docs/` and
# falls back to the basename. Every remaining module basename is unique, so that is legible.
# Located through the imported package rather than an assumed repo layout, so the list
# follows the installed source wherever it lives. os.path.relpath rather than
# Path.relative_to(walk_up=True): the latter is 3.12+, and the docs build runs on 3.11.
_PACKAGE = Path(artefactual.__file__).parent
llms_txt_code_files = [
    f"+:{os.path.relpath(path, _DOCS)}" for path in sorted(_PACKAGE.rglob("*.py")) if path.name != "__init__.py"
]

# HTML output
# The published site, which is where the docs are deployed from .github/workflows/docs.yml.
# sphinx-llms-txt needs it to emit absolute links: without it the entries in llms.txt are
# host-less paths like `/_sources/index.md.txt`, which no consumer can fetch.
html_baseurl = "https://artefactory.github.io/artefactual/"
html_theme = "pydata_sphinx_theme"
html_theme_options = {
    "github_url": "https://github.com/artefactory/artefactual",
    # The switcher belongs with the other controls that change how you are reading rather
    # than what you are reading. Beside the logo it competes with the project name for the
    # same corner, and the theme wraps the navbar rather than shrink either of them.
    "navbar_end": ["version-switcher", "theme-switcher", "navbar-icon-links"],
    # Against the title rather than centred in the remaining space: centring leaves the
    # links floating between two unequal margins, and shifts them as the title changes.
    "navbar_align": "left",
    # The released versions, and which one you are reading. `version_match` is the release
    # string, matching the `version` key the deploy writes into switcher.json; on a
    # development build it matches nothing, which leaves the dropdown listing the releases
    # with none marked current -- correct, because an unreleased build is not among them.
    "switcher": {
        "json_url": f"{SITE_URL}/switcher.json",
        "version_match": release,
    },
    # The theme fetches json_url at build time and *warns* when it cannot be read, which
    # -W turns into a failed build. That fetch would have to succeed before the deploy that
    # publishes the file -- impossible for the release that introduces the switcher, and a
    # network dependency in every build after it. The file's shape is asserted by the deploy
    # that generates it instead.
    "check_switcher": False,
    # The slot is empty by default; the theme puts downloads out of scope, so the component
    # is this repository's own.
    "article_header_end": ["notebook-buttons.html"],
    "show_nav_level": 2,
    "navigation_depth": 3,
    # The page table of contents alone. The default adds a "This Page" block holding one
    # "Show Source" link, which sits under "On this page" saying nothing about the page and
    # serves `_sources/<name>.txt` -- the reStructuredText, or for an example the notebook
    # rendered as a screenful of raw text. A page with no sections is then left with an
    # empty right-hand column, which the theme collapses so the content uses the width.
    "secondary_sidebar_items": ["page-toc"],
    # Reading an archived release should say so on the page rather than only in the
    # dropdown: the banner appears on every version that is not the preferred one, and
    # links to the current release.
    #
    # Off on a development build, which already carries the announcement below. The theme
    # decides from `version_match`, which matches nothing on a `.dev` version, so both would
    # fire and stack two banners saying the same thing -- and the announcement says it
    # better, naming PyPI rather than offering to switch to a version this build has no
    # entry for.
    "show_version_warning_banner": not _is_development_build,
}

# The site is published from the release pipeline, so what it documents is a released
# version and the two cannot disagree. A build from anywhere else -- a pull request, a
# working copy -- says so, because the alternative is a page that reads as published while
# describing an API `pip install artefactual` does not give you.
if _is_development_build:
    html_theme_options["announcement"] = (
        "This is the development version of the documentation. It describes unreleased "
        "changes. The released version is on "
        '<a href="https://pypi.org/project/artefactual/">PyPI</a>.'
    )

# Mermaid renders in the browser, so a diagram is live SVG rather than an image: it selects,
# it scales, and with d3 zoom it pans like the ones GitHub renders. The palette it bakes in
# is light-only, which `_static/mermaid-theme.css` restates in the theme's own variables.
mermaid_d3_zoom = True

# General
templates_path = ["_templates"]
html_static_path = ["_static"]
html_css_files = ["mermaid-theme.css", "notebook-buttons.css"]
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    # Quarto renders the decks into docs/_extra; keep MyST-NB off the sources.
    "presentations/**/*.ipynb",
]

# Rendered decks, copied verbatim into the site root, produced by
# `quarto render docs/presentations`. Listed only when that directory is present: a missing
# extra path is a warning, and the build runs with -W, so naming it unconditionally would
# fail any build that skipped Quarto. An empty directory warns about nothing either way,
# so CI asserts the decks reached the site rather than relying on this entry.
html_extra_path = ["_extra"] if (Path(__file__).parent / "_extra").is_dir() else []
